### PR TITLE
Changes made to allow for deprecated methods in iOS10

### PR DESCRIPTION
**Pull request by FergalMohan**
@adamwulf it's been quite a while since I did a Pull Request so hopefully I haven't messed it up. Please review these changes and see if they make sense. There are a couple of other things to bear in mind,
1. You need to re-add the "text" (string) field to the Message Record and make it queryable (I think)
2. You might need to kill your old subscription to make sure that the SPRMessageTextField "text" field is actually requested as one of the desiredKeys. Let me know if there are any questions.

### CODE REVIEW

**Comment by adamwulf** [comment]
Looks good! If you can make some small adjustments, then I'll merge it in.

First, remove the few `// FM` that are in the code.

Second, the permissions of the files seemed to have gotten changed to 755 from 644, making all of the text files executable. To fix, can you run the following command in your repo:

```
find . -type f -exec chmod 644 {} \;
```

Then recommit and i'll merge in. Thanks!

**Comment by FergalMohan** [comment]
Hi Adam, I did those changes and committed again, let me know if there are any other questions,Fergal

**Comment by adamwulf** [comment]
awesome, thanks! This looks great :)

**Comment by FergalMohan** [comment]
Cool BTW I tested the sample code on iOS9.3 iOS10.3 and iOS11. I notice that the discoverAllUsers.... method doesn't work 100% of the time on iOS11 but seems to be fine on the other 2 iOS versions. Not sure if it was something to do with my iCloud account but there are a lot of complaints online about CloudKit problems having been introduce in iOS11. Just an FYI,
Fergal

**Pull request closed without merging**
